[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "aws.sqs"
license= ["Apache-2.0"]
authors = ["Ballerina"]
version= "3.1.0"
keywords = ["IT Operations/Message Brokers", "Cost/Freemium", "Vendor/Amazon"]
icon= "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.sqs"

[[platform.java21.dependency]]
path = "../native/build/libs/aws.sqs-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "aws.sqs-native"
version = "@project.version@"

